//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigmaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GadgetInstance
    {
        public GadgetInstance()
        {
            this.Settings = new HashSet<GadgetInstanceSetting>();
        }
    
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public byte Row { get; set; }
        public byte Column { get; set; }
        public byte RowSpan { get; set; }
        public byte ColumnSpan { get; set; }
    
        public virtual Gadget Gadget { get; set; }
        public virtual ICollection<GadgetInstanceSetting> Settings { get; set; }
    }
}
