//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigmaWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gadget
    {
        public Gadget()
        {
            this.Instances = new HashSet<GadgetInstance>();
            this.Settings = new HashSet<GadgetSetting>();
        }
    
        public int Id { get; set; }
        public GadgetType GadgetType { get; set; }
        public string SystemName { get; set; }
        public string PublicName { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public string FolderName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string HomePageUrl { get; set; }
        public bool Enabled { get; set; }
        public string Data { get; set; }
    
        public virtual ICollection<GadgetInstance> Instances { get; set; }
        public virtual ICollection<GadgetSetting> Settings { get; set; }
    }
}
